### PR TITLE
Context

### PR DESCRIPTION
**Pull request by Fresheyeball**

### CODE REVIEW

**Comment by groodt** [comment]
Looks smooth! Still a problem with Travis and purescript. :(

Probably unrelated, but it also doesn't use the GHC in our config file.

```
$ export PATH=/usr/local/ghc/$(ghc_find 7.8.3)/bin/:$PATH
ghc_find: error, no such version 7.8.3
```

I've noticed that other purescript projects go brute force and download the tarball of purescript. I think Travis cabal updates don't work.

**Comment by Fresheyeball** [comment]
Yeah, what gives? This method has worked for me for a long time. I wonder why it fails now. Can you link me to one of those projects? I'll just copy paste for Travis.

**Comment by groodt** [comment]
I've no idea. Random searches I did seemed to indicate that they were ok with cabal being up to 2 weeks old because the cabal update is 4MB or something. However, I also found some mentions that they had fixed this, so I'm not sure.

Here is what other purescript projects seem to be doing:
https://github.com/purescript/purescript-free/blob/master/.travis.yml

**Comment by Fresheyeball** [comment]
Ok, so build is passing now. Can @groodt or @michaelficarra check this in runtime real quick? Otherwise I can do it this evening.

**Comment by groodt** [comment]
I'll check it right now. @Fresheyeball

**Comment by groodt** [comment]
:+1: Works just fine on my project for Firefox and Chrome. No warnings in Chrome either. Nice work!

**Comment by Fresheyeball** [comment]
Thank you master @groodt, merging and releasing now

**Comment by Fresheyeball** [comment]
ok, its up on bower `0.0.3`

**Pull request merged**
